// The Spanish mode: the web port's tr() (web/i18n.js), with its dictionaries.
// Text is translated where it is DRAWN -- font_width and font_draw call tr()
// -- not at the call sites that build it, so a string centred by measuring it
// is measured in the language it is drawn in, and no call site changes.
// English is the source; anything without an entry passes through unchanged,
// which is right for car and stage names and for what the player types.
//
// The tables (i18n_es.c) are generated by tools/gen_i18n_es.py from the web
// port's web/i18n*.js; regenerate rather than edit them.
#ifndef NFM_I18N_H
#define NFM_I18N_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

enum { I18N_LANG_EN = 0, I18N_LANG_ES = 1 };

/** The language tr() translates into: I18N_LANG_EN (no translation) or I18N_LANG_ES. */
void i18n_set_lang(int32_t lang);
int32_t i18n_lang(void);

/** `s` in the current language, as the web's tr(): an exact entry; else the
 * entry for `s` without its leading/trailing whitespace (which is kept);
 * else for its whitespace runs flattened to one space; else the first
 * pattern that matches; else, if it has several lines, each line on its
 * own. No match, or English, returns `s` itself.
 *
 * A dictionary hit returns the table's string (lives forever). A composed
 * result (kept whitespace, a pattern, lines) lives in one of I18N_RING
 * static buffers of I18N_BUF bytes, reused round robin: use it before
 * I18N_RING more tr() calls. A result that would not fit returns `s`. */
const char *tr(const char *s);
#define I18N_RING 8
#define I18N_BUF 1024

// ---- the generated tables (i18n_es.c) ----

typedef struct { const char *en, *es; } I18nEntry;

/** A pattern is literal UTF-8 text and these token bytes, anchored at both
 * ends; the replacement says $1..$9 for the captures, in order. */
enum {
  I18N_T_ANY = 1,      // (.*)    captured, greedy
  I18N_T_LAZY = 2,     // (.*?)   captured, shortest first
  I18N_T_ANY1 = 3,     // (.+)
  I18N_T_DIGITS = 4,   // (\d+)
  I18N_T_SDIGITS = 5,  // (-?\d+)
  I18N_T_DIGIT = 6,    // (\d)
  I18N_T_SPACES = 7,   // (\s*)
  I18N_T_NUM = 8,      // ([\d.]+)
  I18N_T_WS = 14,      // \s*     not captured
  I18N_T_WS1 = 15,     // \s+     not captured
  I18N_T_OPT = 16,     // the next byte, optional
  I18N_T_NOT = 17,     // (?!literal): the literal up to I18N_T_END must not follow
  I18N_T_END = 18,
};
typedef struct { const char *re, *to; } I18nPattern;

extern const I18nEntry I18N_ES[];
extern const int32_t I18N_ES_COUNT;
extern const I18nPattern I18N_ES_PATTERNS[];
extern const int32_t I18N_ES_PATTERN_COUNT;

#ifdef __cplusplus
}
#endif

#endif
