# Bakes the text font: Liberation Sans Bold/Regular, the open, metric-compatible
# substitute for the Arial the original draws every string with
# (`new Font("Arial", 1, 13)` and friends in xtGraphics.java).
#
#   python3 tools/bake_font.py path/to/liberation-fonts-ttf-2.1.5
#     -> data/port/font.png        white glyphs, alpha = coverage, at REF px
#     -> native/core/font_data.c   glyph rects and per-size advances
#
# Glyph SHAPES are baked once, large (REF px), and scaled down at draw time
# with mipmaps, so one atlas serves every size and every output resolution.
# ADVANCES are baked per size, hinted, because Java's FontMetrics (fractional
# metrics off) moves the pen by whole hinted pixels -- and these are what
# every centred string's position depends on. FreeType's hinted advances for
# Liberation match Windows' arialbd.ttf/arial.ttf exactly for all 95 printable
# characters at every size below (checked when this script was written).
#
# Past '~' come the EXTRA characters the Spanish text needs (font.c decodes
# UTF-8 and finds them in FONT_EXTRA_CP). They are packed after all the ASCII
# cells, so the ASCII glyphs keep the atlas rects they always had.
#
# Liberation fonts: SIL Open Font License 1.1, see data/port/LiberationSans-OFL.txt.
import os
import sys
from PIL import Image, ImageDraw, ImageFont

REF = 48
PAD = 4
ATLAS_W = 1024
SIZES = (10, 11, 12, 13, 18, 22)
FIRST, LAST = 32, 126
EXTRA = "ÁÉÍÓÚÑÜáéíóúñü¿¡°ºª·×±–—‘’“”•…"
STYLES = (("regular", "LiberationSans-Regular.ttf"), ("bold", "LiberationSans-Bold.ttf"))

root = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
src = sys.argv[1]

CHARS = [chr(c) for c in range(FIRST, LAST + 1)] + sorted(EXTRA)
ASCII_N = LAST - FIRST + 1

def cell(big, ch):
    # Ink bbox from an actual render: getbbox() reports the advance box,
    # not the ink, so bearings would come out as 0.
    tmp = Image.new("L", (3 * REF, 3 * REF), 0)
    ImageDraw.Draw(tmp).text((REF, 2 * REF), ch, font=big, fill=255, anchor="ls")
    ink = tmp.getbbox()
    bbox = (ink[0] - REF, ink[1] - 2 * REF, ink[2] - REF, ink[3] - 2 * REF) if ink else (0, 0, 0, 0)
    return (big, ch, bbox)

advances = [] # per style: per size: list of int
cells = []    # (font, ch, ink bbox relative to the pen on the baseline)
bigs = []
for _, fname in STYLES:
    path = os.path.join(src, fname)
    big = ImageFont.truetype(path, REF)
    bigs.append(big)
    cells += [cell(big, ch) for ch in CHARS[:ASCII_N]]
    advances.append([[int(round(ImageFont.truetype(path, s).getlength(ch)))
                      for ch in CHARS] for s in SIZES])
for big in bigs:
    cells += [cell(big, ch) for ch in CHARS[ASCII_N:]]

# Shelf packing, one row at a time.
x = y = 0
row_h = 0
placed = []
for font, ch, (l, t, r, b) in cells:
    w, h = max(r - l, 0), max(b - t, 0)
    if x + w + 2 * PAD > ATLAS_W:
        x, y, row_h = 0, y + row_h, 0
    placed.append((x + PAD, y + PAD, w, h, l, t))
    x += w + 2 * PAD
    row_h = max(row_h, h + 2 * PAD)
atlas_h = 1
while atlas_h < y + row_h:
    atlas_h *= 2

img = Image.new("RGBA", (ATLAS_W, atlas_h), (255, 255, 255, 0))
alpha = Image.new("L", img.size, 0)
draw = ImageDraw.Draw(alpha)
for (font, ch, _), (ax, ay, w, h, l, t) in zip(cells, placed):
    if w and h:
        draw.text((ax - l, ay - t), ch, font=font, fill=255, anchor="ls")
img.putalpha(alpha)
# Back to [style][glyph] order: ASCII then EXTRA within each style.
E = len(EXTRA)
placed = (placed[:ASCII_N] + placed[2 * ASCII_N:2 * ASCII_N + E] +
          placed[ASCII_N:2 * ASCII_N] + placed[2 * ASCII_N + E:])
img.save(os.path.join(root, "data", "port", "font.png"), optimize=True)

n = len(CHARS)
out = []
out.append("// Generated by tools/bake_font.py -- do not edit; rebake instead.")
out.append('#include "font.h"\n')
out.append(f"const int32_t FONT_REF = {REF};")
out.append(f"const int32_t FONT_ATLAS_W = {ATLAS_W}, FONT_ATLAS_H = {atlas_h};")
out.append(f"const int32_t FONT_SIZES[FONT_SIZE_COUNT] = {{{', '.join(map(str, SIZES))}}};\n")
out.append(f"_Static_assert(FONT_GLYPH_COUNT == {n}, \"font.h's FONT_GLYPH_COUNT is stale\");")
out.append(f"_Static_assert(FONT_EXTRA_COUNT == {len(EXTRA)}, \"font.h's FONT_EXTRA_COUNT is stale\");\n")
out.append("// Codepoint of glyph FONT_GLYPH_COUNT - FONT_EXTRA_COUNT + i, ascending")
out.append("const uint16_t FONT_EXTRA_CP[FONT_EXTRA_COUNT] = {" + ", ".join(f"0x{ord(c):04x}" for c in CHARS[ASCII_N:]) + "};\n")
out.append("// [style][char - 32] = {atlas x, atlas y, w, h, left bearing, top (from baseline)} at FONT_REF px")
out.append("const FontGlyph FONT_GLYPHS[2][FONT_GLYPH_COUNT] = {")
for s in range(2):
    out.append("  {")
    for i in range(n):
        ax, ay, w, h, l, t = placed[s * n + i]
        ch = CHARS[i] if i < ASCII_N else f"U+{ord(CHARS[i]):04X}"
        out.append(f"    {{{ax}, {ay}, {w}, {h}, {l}, {t}}}, // {ch!r}")
    out.append("  },")
out.append("};\n")
out.append("// [style][size index][char - 32] = hinted advance in px")
out.append("const uint8_t FONT_ADVANCE[2][FONT_SIZE_COUNT][FONT_GLYPH_COUNT] = {")
for s in range(2):
    out.append("  {")
    for row in advances[s]:
        out.append("    {" + ", ".join(map(str, row)) + "},")
    out.append("  },")
out.append("};")
with open(os.path.join(root, "native", "core", "font_data.c"), "w", newline="\n") as f:
    f.write("\n".join(out) + "\n")
print("font.png", img.size, "glyphs", len(placed))
